### ISSUE TITLE
PID presentation for (Q)EAA issuance

### ISSUE THREAD

**Issue by balanza** [italia/eidas-it-wallet-docs#144]
(Q)EAA issuance requires a credential presentation in order to authorize User to request the credential. As stated in the [specification](https://github.com/italia/eudi-wallet-it-docs/blob/a601d8a9132305884f2c9e208dc0259a81721e4a/docs/en/pid-eaa-issuance.rst): 

> The (Q)EAA Provider performs the User authentication requesting a valid PID to the Wallet Instance. The (Q)EAA Provider MUST use [OpenID4VP] to dynamically request the presentation of the PID. From a protocol perspective, the (Q)EAA Provider then acts as a Relying Party and provide the presentation request to the Wallet Instance. The Wallet Instance MUST have a valid PID obtained prior to start the transaction with the (Q)EAA Provider.

This part is left undefined, and we might converge to a specification.

**Comment by balanza** [comment]
The first thing we should clarify is whether we aim for a complete specification or a pragmatic approach.

Given that we planned to deploy credentials that only require PID verification to be emitted in the first phase, it may be reasonable to agree on a fixed claim set to be provided, without a proper claims negotiation as defined in https://openid.net/specs/openid-4-verifiable-presentations-1_0.html.

Otherwise, we might decide to work on a general-purpose specification as defined in https://github.com/italia/eudi-wallet-it-docs/issues/145.

**Comment by peppelinux** [comment]
@balanza I would suggest to use the editor's draft
https://openid.github.io/OpenID4VP/openid-4-verifiable-presentations-wg-draft.html

since it is on the way an important discussion in the DCP WG about using PE v3 and a potential new born of an implementation profile of PE for OpenID4VC I see two options and I would ask you which one you prefer:

1. defining the supported request scopes within the italian technical specs
2. deciding to concretely use PE v2.0 with future breaking changes in account

**Comment by peppelinux** [comment]
Here the requirement to define the supproted scopes, and its mapping to the digital credential format and content, in the specs

**Comment by peppelinux** [comment]
This statement of the problem is superseeded with the following issue:
https://github.com/italia/eudi-wallet-it-docs/issues/152

It defines the requirements in a more technical way with the aims to give an implementative solution as well.
