### ISSUE TITLE
Trust artifacts and protocols

### ISSUE THREAD

**Issue by fmarino-ipzs** [italia/eidas-it-wallet-docs#244]
We should add:
- normative text about the Entity Configuration and Metadata for all entities
- protocol details (normative and non-normative examples) about how the trust must be established

**Comment by peppelinux** [comment]
@fmarino-ipzs in which section it is supposed to be done?

I would suggest to move this in the next milestone (v0.8), since we're working with other member states in several contexts on this topic.
Once we'll have completed the work we'll be therefore able to merge in this specification the relevan parts for the resolution of this issue

**Comment by fmarino-ipzs** [comment]
The first part of this issue is covered by PR #328. I will create a new issue about the second part.

**Comment by fmarino-ipzs** [comment]
The new issue can be found in Issue #332
