### ISSUE TITLE
[Wallet Attestation - Requirements ] Req.9 Loss of Wallet Istance private key

### ISSUE THREAD

**Issue by pietroACN** [italia/eidas-it-wallet-docs#257]
The requirement states: "When the private key associated with the Wallet Instance is lost or deleted, the attestation MUST become invalid to prevent unauthorized use of the Wallet Instance".  [Link ](https://github.com/italia/eudi-wallet-it-docs/blob/df948503e22cbf949530a07b6cee0e83e6901613/docs/en/wallet-attestation.rst?plain=1#L33C1-L33C168)

This requirement is unclear:
1) Wallet Attestation is signed by Wallet Provider, while this requirement refers to Wallet Instance private key.
2) If this key lost how does the wallet owner can act within its wallet and 'invalidate' this attestation? 
3) How does the attestation 'becomes' invalid? 
4) If owner communicates asynchronously this information to Wallet Provider (for example via a specific properly authenticated web page managed by WP itself) user will not be able to identify himself via his private key as it's lost, thus will need similar (L3) methods to securely identify. In any case how WP will be able to send an update to the wallet about Wallet Attestation revocation?

This requirement needs to be well detailed with a proper asynchronous process to avoid misuse.

**Comment by peppelinux** [comment]
1. WIA is signed by WP, at the same time the WIA binds the WI's public key (cnf.jwk). This means that at least two keys are involved for this issuance.
2. several channels must be taken into account, since there's the need to allow users that lost their phones to be able to deactivate them. This is out of the scopes of the specification, while represent security impacts within the wallet solution. Therefore a better explainataion about, at east, this requirement and some implementations consideration would help
3. it can be revoked or it is simply short-lived. At this stage in the italian specs we only deal with short liveld attestations
4. legacy eID systems and/or remote id proofing methods must be involved in these cases. The revocation is related to the wallet instance and not to its wallet attestation. This can be further analyzied in terms of security impacts.

please provide the solution you consider valuable for the resolution of this issue
