### ISSUE TITLE
Device Integrity Service from a Federative perspective

### ISSUE THREAD

**Issue by peppelinux** [italia/eidas-it-wallet-docs#269]
Is the Device Integrity Service part of the federation or not?

**Comment by peppelinux** [comment]
Is the Device Integrity Service discovered by the Wallet instance or is it hard coded ?

**Comment by grausof** [comment]
Device Integrity Service is something proprietary to the device's operating system and accessible exclusively via the vendor's SDK (Android or iOS) therefore there is no hardcoded URL nor is it possible to make it part of the federation. However, since it is a custom implementation between Wallet Instance and Wallet Provider, I don't think this part should be regulated.

**Comment by peppelinux** [comment]
During the editor's call of the 13 May 2024, we agreed that the current text requires further clarification about this aspect, therefore a PR is going to be provided in for the milestone 0.7.1

**Comment by grausof** [comment]
I noticed that this information was already present in the notes relating to the `Attestation Service`. through this [PR](https://github.com/italia/eudi-wallet-it-docs/pull/281) I tried to explain them better.
