### ISSUE TITLE
[Attestation Revocation] JWT/CWT/Accumulators based revocation mechanisms

### ISSUE THREAD

**Issue by peppelinux** [italia/eidas-it-wallet-docs#5]
Privacy preserving status list

https://github.com/vcstuff/draft-looker-jwt-cwt-status-list
https://vcstuff.github.io/draft-looker-jwt-cwt-status-list/draft-looker-jwt-cwt-status-list.html

**Comment by peppelinux** [comment]
in addition to the current draft related to the status list we're looking also to the anonymous accumulators proposed by sweden

here the will to collect in this issue all the related material to be considered for developments

**Comment by alenhorvat** [comment]
Hi. Status lists are not very privacy preserving. Please see https://api-pilot.ebsi.eu/docs/specs/credential-status-framework/credential-status-vcs - an extensive analysis has been performed in collaboration with other experts.

Advanced cryptographic approaches have also been analysed but are not presented since use cases discarded them.

**Comment by peppelinux** [comment]
Thank you @alenhorvat 

this issue is going to be closed since the discussion is moving to have status list and [status attestations](https://github.com/peppelinux/draft-demarco-status-attestations) for different use cases and credential types.
